name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    container: archlinux:latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm go libqalculate pkgconf gcc

    - name: Setup Go
      working-directory: ./src
      run: go mod download

    - name: Build binaries
      working-directory: ./src
      run: |
        # Linux AMD64
        GOOS=linux GOARCH=amd64 go build -o ../nasc-linux-amd64 -v .

        # Linux ARM64
        GOOS=linux GOARCH=arm64 go build -o ../nasc-linux-arm64 -v .

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          nasc-linux-amd64
          nasc-linux-arm64
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}